# -*- coding: utf-8 -*-
"""Sales_Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OF0hPStZkUTtbiiPIWF3xQSAvDH3SEGk

The goal of this project is to build a forecasting tool to help a retail business plan inventory. By predicting daily sales, we aim to reduce overstocking risks and ensure enough supply for high-demand periods like the holidays.

url of the data resource: https://archive.ics.uci.edu/dataset/352/online+retail
"""

!unzip "/content/online+retail.zip" -d "/content"

import numpy as np
import pandas as pd
import datetime as dt

d=pd.read_excel("/content/Online Retail.xlsx")

d.head()

len(d)

d.describe()

d.info()

d = d[d['CustomerID'].notna()]#deleting rows with no customerid

d['CustomerID'] = d['CustomerID'].astype(int)

d['Quantity'] = d['Quantity'].abs()#fixing the negative values

d['InvoiceNo'] = d['InvoiceNo'].astype(str).str.replace(r'\D', '', regex=True)#setting invoice into digits only

d = d[d["UnitPrice"] != 0]

d["InvoiceDate"] = d["InvoiceDate"].apply(pd.to_datetime)

prefixes = d['InvoiceNo'].astype(str).str.extract(r'(^[^0-9])')[0].unique()#checking if the invoice has alphabet

prefixes

d.duplicated().sum()

d = d.drop_duplicates()#deleting duplicates

d['Total'] = d['Quantity'] * d['UnitPrice']

d.describe()

d.info()

d.isnull().sum()

d.nunique()

d['Country'].value_counts()

most_exp = d.loc[d['UnitPrice'] == d['UnitPrice'].max()]
most_exp

cheap = d.loc[d['UnitPrice'] == d['UnitPrice'].min()]
cheap





import matplotlib.pyplot as plt


customer_spend = d.groupby('CustomerID')['Total'].sum().reset_index()

top_customers = customer_spend.sort_values(by='Total', ascending=False).head(10)


top_customers['CustomerID'] = top_customers['CustomerID'].astype(int).astype(str)

plt.figure(figsize=(12, 6))


colors = plt.cm.plasma_r(np.linspace(0, 1, 10))


bars = plt.bar(top_customers['CustomerID'], top_customers['Total'], color=colors)


plt.xlabel('Customer ID', fontsize=12)
plt.ylabel('Total Amount, £', fontsize=12)
plt.title('Top Customers by Total Purchase Amount', fontsize=14)


for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 20000,
             f'£{int(yval/1000)}k',
             va='top', ha='center', color='black', fontweight='bold')
plt.ylim(0, max(top_customers['Total']) * 1.2)
plt.show()

rare_customers = customer_spend.sort_values(by='Total', ascending=True).head(10)

rare_customers['CustomerID'] = rare_customers['CustomerID'].astype(int).astype(str)

plt.figure(figsize=(12, 6))
bars = plt.bar(rare_customers['CustomerID'], rare_customers['Total'], color=colors)

plt.xlabel('Customer ID', fontsize=12)
plt.ylabel('Total Amount, £', fontsize=12)
plt.title('Customers with Lowest Total Purchase Amount', fontsize=14)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + (yval * 0.01),
             f'£{round(yval, 2)}',
             va='bottom', ha='center', color='black', fontweight='bold')

plt.ylim(0, max(rare_customers['Total']) * 1.2)
plt.show()





country_spend = d.groupby('Country')['Total'].sum().reset_index()

top_countries = country_spend.sort_values(by='Total', ascending=False).head(10)

plt.figure(figsize=(12, 6))

colors = plt.cm.viridis_r(np.linspace(0, 0.7, 10))

bars = plt.bar(top_countries['Country'], top_countries['Total'], color=colors)

plt.xlabel('Country', fontsize=12)
plt.ylabel('Total Amount, £', fontsize=12)
plt.title('Top Countries by Total Purchase Amount', fontsize=14)

for bar in bars:
    yval = bar.get_height()

    plt.text(bar.get_x() + bar.get_width()/2, yval + (yval * 0.01),
             f'£{int(yval/1000)}k',
             va='bottom', ha='center', fontsize=10, fontweight='bold')


plt.ylim(0, max(top_countries['Total']) * 1.15)
plt.tight_layout()
plt.show()







import matplotlib.pyplot as plt
import numpy as np

top_products = d.groupby('Description')['Quantity'].sum().reset_index()
top_products = top_products.sort_values(by='Quantity', ascending=False).head(10)

plt.figure(figsize=(12, 8))
colors = plt.cm.magma(np.linspace(0.4, 0.8, 10))

bars = plt.barh(top_products['Description'], top_products['Quantity'], color=colors[::-1])

plt.xlabel('Quantity Sold', fontsize=12, fontweight='bold')
plt.title('Top 10 Best Selling Products', fontsize=15, fontweight='bold', pad=20)

for bar in bars:
    width = bar.get_width()
    plt.text(width + (width * 0.01),
             bar.get_y() + bar.get_height()/2,
             f'{int(width)}',
             va='center',
             ha='left',
             fontsize=10,
             fontweight='bold')

plt.gca().invert_yaxis() # Putting the #1 product at the top
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

top_revenue_products = d.groupby('Description')['Total'].sum().reset_index()

top_revenue_products = top_revenue_products.sort_values(by='Total', ascending=False).head(10)

plt.figure(figsize=(12, 8))
colors = plt.cm.viridis(np.linspace(0.3, 0.8, 10))

bars = plt.barh(top_revenue_products['Description'], top_revenue_products['Total'], color=colors[::-1])

plt.xlabel('Total Revenue (£)', fontsize=12, fontweight='bold')
plt.title('Top 10 Products by Revenue', fontsize=15, fontweight='bold', pad=20)

for bar in bars:
    width = bar.get_width()
    plt.text(width + (width * 0.01),
             bar.get_y() + bar.get_height()/2,
             f'£{int(width/1000)}k',
             va='center',
             ha='left',
             fontsize=10,
             fontweight='bold')

plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()



d['InvoiceDate'].describe()

d['YearMonth'] = d['InvoiceDate'].dt.to_period('M').astype(str)

monthly_sales = d.groupby('YearMonth')['Total'].sum().reset_index()

plt.figure(figsize=(12, 6))
plt.plot(monthly_sales['YearMonth'], monthly_sales['Total'], marker='o', color='darkorange', linewidth=2)

plt.title('Total Sales Revenue by Month', fontsize=15, fontweight='bold')
plt.xlabel('Month', fontsize=12)
plt.ylabel('Total Sales (£)', fontsize=12)
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

peak_month = monthly_sales.loc[monthly_sales['Total'].idxmax()]
print(f"The highest sales were in {peak_month['YearMonth']} with a total of £{peak_month['Total']:,.2f}")

d['Hour'] = d['InvoiceDate'].dt.hour

hourly_sales = d.groupby('Hour')['InvoiceNo'].nunique().reset_index()

plt.figure(figsize=(10, 6))
plt.bar(hourly_sales['Hour'], hourly_sales['InvoiceNo'], color='skyblue', edgecolor='navy')

plt.title('Number of Orders by Hour of Day', fontsize=15, fontweight='bold')
plt.xlabel('Hour (24-hour format)', fontsize=12)
plt.ylabel('Number of Unique Invoices', fontsize=12)
plt.xticks(range(0, 25))
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()



"""Based on these 2 figures:

Seasonality: We can see a massive spike in November. In retail datasets, this is common due to "Black Friday" and early Christmas shopping.

Most sales peak between 10:00 AM and 1:00 PM.
"""

d['DayName'] = d['InvoiceDate'].dt.day_name()
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
daily_sales = d.groupby('DayName')['Total'].sum().reindex(day_order)

daily_sales.plot(kind='bar', color='salmon', figsize=(8, 5))
plt.title('Sales by Day of the Week')
plt.show()









daily_data = d.copy()

daily_data.set_index('InvoiceDate', inplace=True)

daily_sales = daily_data['Total'].resample('D').sum().reset_index()

daily_sales.columns = ['Date', 'TotalSales']

daily_sales.head()

daily_sales['Date'] = pd.to_datetime(daily_sales['Date'])


daily_sales['DayName'] = daily_sales['Date'].dt.day_name()

daily_sales.head()

daily_sales_clean = daily_sales[daily_sales['TotalSales'] > 0].copy()#days w/o saturdays

daily_sales_clean.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(15, 6))
plt.plot(daily_sales_clean['Date'], daily_sales_clean['TotalSales'], color='tab:blue', label='Daily Sales')

daily_sales_clean['7_Day_MA'] = daily_sales_clean['TotalSales'].rolling(window=7).mean()
plt.plot(daily_sales_clean['Date'], daily_sales_clean['7_Day_MA'], color='orange', linewidth=2, label='7-Day Moving Average')

plt.title('Daily Sales Over Time', fontsize=16)
plt.ylabel('Total Sales (£)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()



daily_sales_clean['Month'] = daily_sales_clean['Date'].dt.month
daily_sales_clean['DayOfWeek'] = daily_sales_clean['Date'].dt.dayofweek #0=Monday, 6=Sunday
daily_sales_clean['Quarter'] = daily_sales_clean['Date'].dt.quarter

daily_sales_clean['Lag_1'] = daily_sales_clean['TotalSales'].shift(1)

daily_sales_clean['Rolling_7'] = daily_sales_clean['TotalSales'].rolling(window=7).mean()

daily_sales_clean = daily_sales_clean.dropna()

daily_sales_clean.head()

cutoff_date = '2011-11-01'#for trainning and testing

train = daily_sales_clean[daily_sales_clean['Date'] < cutoff_date]
test = daily_sales_clean[daily_sales_clean['Date'] >= cutoff_date]

print(f"Training Days: {train.shape[0]}")
print(f"Testing Days: {test.shape[0]}")

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(train['Date'], train['TotalSales'], label='Training Data', color='blue')
plt.plot(test['Date'], test['TotalSales'], label='Testing Data', color='orange')
plt.title('Train / Test Split', fontsize=16)
plt.legend()
plt.show()

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

features = ['Month', 'DayOfWeek', 'Quarter', 'Lag_1', 'Rolling_7']
target = 'TotalSales'

X_train = train[features]
y_train = train[target]

X_test = test[features]
y_test = test[target]

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
print(f"Mean Absolute Error: £{mae:,.2f}")
print(f"Average Daily Sales in Test Set: £{y_test.mean():,.2f}")



import matplotlib.pyplot as plt

results = pd.DataFrame({'Date': test['Date'], 'Actual': y_test, 'Predicted': predictions})
results = results.sort_values('Date')

plt.figure(figsize=(14, 7))

plt.plot(results['Date'], results['Actual'], label='Actual Sales (Reality)', color='blue', linewidth=2, alpha=0.7)

plt.plot(results['Date'], results['Predicted'], label='Predicted Sales (Model)', color='orange', linestyle='--', linewidth=2.5)

plt.title('Forecast vs Reality', fontsize=16, fontweight='bold')
plt.ylabel('Total Sales (£)', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)

plt.show()



from sklearn.linear_model import LinearRegression


lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

lr_predictions = lr_model.predict(X_test)

lr_mae = mean_absolute_error(y_test, lr_predictions)

print(f"Linear Regression MAE: £{lr_mae:,.2f}")
print(f"Average Daily Sales in Test Set: £{y_test.mean():,.2f}")

plt.figure(figsize=(14, 7))

plt.plot(results['Date'], results['Actual'], label='Actual Sales', color='blue', alpha=0.6, linewidth=2)

plt.plot(results['Date'], results['Predicted'], label='Random Forest', color='orange', linestyle='--', linewidth=2)

plt.plot(test['Date'], lr_predictions, label='Linear Regression', color='green', linestyle=':', linewidth=2)

plt.title('Model Comparison: Linear vs Random Forest', fontsize=16)
plt.ylabel('Total Sales (£)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

